language: java

cache:
  directories:
  - "$HOME/google-cloud-sdk/"
  - "$HOME/.m2"

before_install:
- openssl aes-256-cbc -K $encrypted_4cd52d8a0d11_key -iv $encrypted_4cd52d8a0d11_iv -in client-secret.json.enc -out client-secret.json -d
- gcloud version || true
- if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
# Add gcloud to $PATH
- source $HOME/google-cloud-sdk/path.bash.inc
- gcloud version
- gcloud components update kubectl
- gcloud auth activate-service-account --key-file client-secret.json
- gcloud config set project code-and-play
- gcloud config set compute/zone europe-west3-c
- gcloud container clusters get-credentials cap
- kubectl get ns

#before_script:
#- ./scripts/image-prepare.sh $FULL_IMAGE_NAME
#- ./scripts/image-push.sh $FULL_IMAGE_NAME

#script:
#- ./scripts/gcloud-select-cluster.sh $CLUSTER_NAME
#- ./scripts/k8s-run-mysql.sh ''
