
# this config is used in addition to application.yml during test.

spring:
  datasource:
    url: jdbc:h2:mem:data;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE

logging:
  level:
    org.hibernate.SQL: trace
    org.hibernate.type: trace
