apiVersion: v1
kind: Service
metadata:
  name: ${SERVICE_NAME}
  #namespace: services
  labels:
    app: ${SERVICE_NAME}
    channel: ${TRAVIS_BRANCH}
spec:
  selector:
    app: ${SERVICE_NAME}
    channel: ${TRAVIS_BRANCH}
  ports:
  - port: 8080
    targetPort: 8080
    name: http